---
- name:  create system user for sonar
  user:
    name: sonar
    createhome: no
    shell: /bin/nologin

- name: install unzip
  package:
    name: unzip

- name: extract sonarqube archive
  unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{sonarqube_version}}.zip
    dest: /opt/
    keep_newer: yes
    owner: sonar
    group: sonar
    remote_src: yes

- name: send sonarqube service template
  template:
    src: templates/sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service

- name: launch sonarqube service
  systemd:
    name: sonarqube
    state: started
    enabled: yes
    daemon_reload: yes